spring.application.name=Parking-System
#PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/parking_system_db
spring.datasource.username=postgres
spring.datasource.password=Manoj@123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto = update

spring.jackson.serialization.write-dates-as-timestamps=false
